### PR TITLE
Updated to version 2.3.0 of Vocal

### PR DESCRIPTION
**Pull request by realProngsDark**

### CODE REVIEW

**Comment by realProngsDark** [comment]
I ran flatpak-builder using my modified json and the theme seems a little broken. I have no prior experience with flatpak so I really don't know what went wrong

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
OK - I'll look into this a bit more closely. This manifest should likely be changed to use the elementary baseapp and a few other tweaks.

**Comment by nedrichards** [comment]
I'm not sure what went wrong in your case, but by and large for elementary apps we patch to force the elementary theme and icons since the apps are designed specifically for that. I'm going to close this in favour of my PR at https://github.com/flathub/com.github.needleandthread.vocal/pull/6 however thanks very much for the push and the exploration. I hope you continue to enjoy flatpak!

**Pull request closed without merging**
