### PR TITLE
Update runtime and BaseApp, tweak permissions

### LINKED ISSUE #13: Update runtime from 3.36?
```
[kyle@discovery ~]$ flatpak update com.github.needleandthread.vocal
Looking for updates…
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.needleandthread.vocal
```

### PR DESCRIPTION
**Pull request by lionirdeadman**
Runtime and BaseApp need to be updated as they are EOL
GVFS access was added to work properly
home and tmp have been removed as they are unneeded for the application to work

Fix #13

### CODE REVIEW

**Comment by kmoad** [comment]
Downloaded from testing and clicked around without issues.

**Comment by kmoad** [comment]
App is noticeably laggy. Forwarding issue to upstream developers.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
I'll merge this.

**Comment by kmoad** [comment]
Thanks folks!

**Pull request merged**
